extends: existence
message: "Точка перед русской буквой в '%s'. Возможно, пропущен пробел после точки."
level: error
scope: text
raw:
  - '(?i)\.[а-яё]'
exceptions:
  - '(?i)\b(т\.д|т\.п|т\.к|и\.о|т\.е|руб)\.'