extends: existence
message: "Точка перед русской буквой в '%s'. Возможно, пропущен пробел после точки."
level: error
scope: raw
raw:
  - '\.\p{Cyrillic}'
exceptions:
  - '(?i)(т\.д|т\.п|т\.к|и\.о|т\.е|н\.в|руб)\.'